export const Questions = [
    {
      prompt: "What is the output of `console.log(typeof [])` in JavaScript?",
      optionA: "object",
      optionB: "array",
      optionC: "null",
      optionD: "undefined",
      answer: "optionA",
    },
    {
      prompt: "Which HTML tag is used to define an internal style sheet?",
      optionA: "<css>",
      optionB: "<script>",
      optionC: "<style>",
      optionD: "<link>",
      answer: "optionC",
    },
    {
      prompt: "What does CSS stand for?",
      optionA: "Computer Style Sheets",
      optionB: "Creative Style Sheets",
      optionC: "Cascading Style Sheets",
      optionD: "Colorful Style Sheets",
      answer: "optionC",
    },
    {
      prompt: "Which company developed the Java programming language?",
      optionA: "Microsoft",
      optionB: "Apple",
      optionC: "Sun Microsystems",
      optionD: "Oracle",
      answer: "optionC",
    },
    {
      prompt: "In Python, what does the `len()` function do?",
      optionA: "Returns the number of items in an object",
      optionB: "Returns the length of a string",
      optionC: "Returns the data type of an object",
      optionD: "Returns the size of a variable",
      answer: "optionA",
    },
    {
      prompt: "What is the main purpose of the git version control system?",
      optionA: "To compile code",
      optionB: "To track changes in source code",
      optionC: "To execute code",
      optionD: "To deploy applications",
      answer: "optionB",
    },
    {
      prompt: "What does HTTP stand for?",
      optionA: "HyperText Transfer Protocol",
      optionB: "HyperTransfer Text Protocol",
      optionC: "Hyperlink Transfer Text Protocol",
      optionD: "Hyper Transfer Text Process",
      answer: "optionA",
    },
    {
      prompt: "Which of the following is a NoSQL database?",
      optionA: "MySQL",
      optionB: "PostgreSQL",
      optionC: "Oracle",
      optionD: "MongoDB",
      answer: "optionD",
    },
    {
      prompt: "In HTML, which attribute is used to specify an alternate text for an image, if the image cannot be displayed?",
      optionA: "src",
      optionB: "title",
      optionC: "alt",
      optionD: "href",
      answer: "optionC",
    },
    {
      prompt: "Which of the following is a correct way to declare a variable in JavaScript?",
      optionA: "var myVar;",
      optionB: "dim myVar;",
      optionC: "let myVar;",
      optionD: "myVar = var;",
      answer: "optionA",
    },
  ];
  

  